<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>DeckTrackerReconnectPlugin</RootNamespace>
    <AssemblyName>DeckTrackerReconnectPlugin</AssemblyName>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Hearthstone Deck Tracker">
      <HintPath>references\Hearthstone Deck Tracker.exe</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows" />
    <Reference Include="System.Windows.Controls.Ribbon" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Presentation" />
    <Reference Include="System.Xaml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UtilLib\UtilLib.csproj" />
  </ItemGroup>

</Project>
